# Generated by Django 2.2.2 on 2019-11-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='DEFAULT VALUE', max_length=25)),
                ('last_name', models.CharField(default='DEFAULT VALUE', max_length=25)),
                ('address', models.CharField(max_length=80)),
                ('email', models.CharField(blank=True, max_length=50, unique=True)),
                ('cover_image', models.ImageField(upload_to='uploads')),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('phone_no', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('0', 'male'), ('1', 'Female'), ('2', 'others')], max_length=1)),
                ('created_by', models.CharField(max_length=15)),
            ],
        ),
    ]
