# Generated by Django 2.2.2 on 2019-08-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80)),
                ('user_picture', models.ImageField(upload_to='uploads')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('cover_image', models.ImageField(upload_to='uploads')),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('phone_no', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('0', 'male'), ('1', 'Female'), ('2', 'others')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Friends',
            },
        ),
    ]
