# Generated by Django 2.2.2 on 2019-11-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='first_name',
            new_name='firstname',
        ),
    ]
