# Generated by Django 2.2.2 on 2019-08-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={},
        ),
        migrations.RemoveField(
            model_name='friends',
            name='email',
        ),
    ]
