# Generated by Django 2.2.2 on 2019-11-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20191113_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
