# Generated by Django 2.2.2 on 2019-08-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20190818_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='email',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='friends',
            name='first_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=25),
        ),
        migrations.AddField(
            model_name='friends',
            name='last_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=25),
        ),
    ]
