# Generated by Django 2.2.2 on 2019-08-18 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20190818_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='user_picture',
        ),
        migrations.AddField(
            model_name='friends',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
