# Generated by Django 2.2.2 on 2019-08-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_auto_20190819_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='created_by',
            field=models.CharField(max_length=15),
        ),
    ]
