# Generated by Django 2.2.2 on 2019-11-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_auto_20191110_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='created_at',
        ),
    ]
